# Generated by Django 2.0.8 on 2018-10-14 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notifications_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['created_at']},
        ),
    ]
