# Generated by Django 2.0.8 on 2018-09-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_image_tages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='tages',
            new_name='tags',
        ),
    ]
